# Generated by Django 4.2.5 on 2023-10-28 19:02

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('en_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('tagline', models.CharField(default='-', max_length=200, null=True)),
                ('year', models.SmallIntegerField()),
                ('country', models.CharField(max_length=80)),
                ('watch_time', models.CharField(default='', max_length=40)),
                ('poster', models.URLField(default='')),
                ('world_premier', models.DateField(default=datetime.date.today)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('en_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('in_bookmarks', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_database.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('en_name', models.CharField(max_length=100, null=True, unique=True)),
                ('photo', models.URLField()),
                ('birth_day', models.DateField(default=datetime.date.today)),
                ('death_day', models.DateField(blank=True, default=None, null=True)),
                ('profession', models.ManyToManyField(to='movies_database.profession')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actor', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='composers',
            field=models.ManyToManyField(related_name='film_composer', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='designers',
            field=models.ManyToManyField(related_name='film_designer', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='film_director', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='editors',
            field=models.ManyToManyField(related_name='film_editor', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='film_genres', to='movies_database.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='operators',
            field=models.ManyToManyField(related_name='film_operator', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(related_name='film_producer', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenwriters',
            field=models.ManyToManyField(related_name='film_screenwriter', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='watchers',
            field=models.ManyToManyField(related_name='my_watched_movies', through='movies_database.UserMovieRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
