# Generated by Django 4.2.5 on 2023-12-07 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermovierelation',
            unique_together={('user', 'movie')},
        ),
    ]
