# Generated by Django 4.2.5 on 2023-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.SmallIntegerField(),
        ),
    ]
