# Generated by Django 4.2.5 on 2023-11-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0002_alter_person_birth_day_alter_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='composers',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='designers',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='operators',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='producers',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='screenwriters',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profession',
        ),
        migrations.AddField(
            model_name='movie',
            name='crew',
            field=models.ManyToManyField(related_name='person_movies', through='movies_database.Profession', to='movies_database.person'),
        ),
        migrations.AddField(
            model_name='profession',
            name='movie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies_database.movie'),
        ),
        migrations.AddField(
            model_name='profession',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies_database.person'),
        ),
    ]
