# Generated by Django 4.2.5 on 2023-12-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0002_alter_usermovierelation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierelation',
            name='review',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
