# Generated by Django 4.2.5 on 2024-01-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0003_alter_usermovierelation_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovierelation',
            name='will_watch',
            field=models.BooleanField(default=False),
        ),
    ]
