# Generated by Django 4.2.5 on 2023-11-02 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0003_remove_movie_actors_remove_movie_composers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='movie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_database.movie'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies_database.person'),
        ),
    ]
