# Generated by Django 4.2.5 on 2023-09-15 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_database', '0004_usermovierelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watchers',
            field=models.ManyToManyField(related_name='my_watched_movies', through='movies_database.UserMovieRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
