# Generated by Django 4.2.5 on 2024-01-08 07:44

from django.db import migrations, models
import movies_database.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0004_usermovierelation_will_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movies_database.models.get_upload_path),
        ),
    ]
