# Generated by Django 4.2.5 on 2023-09-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0005_movie_watchers_alter_movie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierelation',
            name='rate',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
