# Generated by Django 4.2.5 on 2023-11-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0005_alter_profession_en_name_alter_profession_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='en_name',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='profession',
            name='en_name',
            field=models.SlugField(),
        ),
    ]
