# Generated by Django 4.2.5 on 2023-09-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0006_alter_usermovierelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
