# Generated by Django 4.2.5 on 2023-11-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0006_alter_genre_en_name_alter_profession_en_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='en_name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='en_name',
            new_name='slug',
        ),
    ]
