# Generated by Django 4.2.5 on 2023-11-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0007_rename_en_name_genre_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovierelation',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
