# Generated by Django 4.2.5 on 2023-11-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0008_usermovierelation_is_watched_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovierelation',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
