# Generated by Django 4.2.5 on 2023-10-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0008_actor_director_genre_producer_screenwriter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
