# Generated by Django 4.2.5 on 2023-11-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0009_usermovierelation_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='usermovierelation',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
