# Generated by Django 4.2.5 on 2023-10-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0009_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True),
        ),
    ]
