# Generated by Django 4.2.5 on 2023-10-05 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0011_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierelation',
            name='rate',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
