# Generated by Django 4.2.5 on 2023-10-07 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0012_alter_usermovierelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='birth_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='actor',
            name='death_day',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='birth_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='director',
            name='death_day',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='birth_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='producer',
            name='death_day',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='birth_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='screenwriter',
            name='death_day',
            field=models.DateField(default=None, null=True),
        ),
    ]
