# Generated by Django 4.2.5 on 2023-10-07 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0013_actor_birth_day_actor_death_day_director_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierelation',
            name='rate',
            field=models.PositiveSmallIntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
