# Generated by Django 4.2.5 on 2023-10-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0014_alter_usermovierelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
