# Generated by Django 4.2.5 on 2023-10-07 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0016_alter_usermovierelation_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermovierelation',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
