# Generated by Django 4.2.5 on 2023-10-12 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0017_alter_usermovierelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='world_premier',
            field=models.DateField(default=datetime.date(2023, 10, 12)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
