# Generated by Django 4.2.5 on 2023-10-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0018_movie_world_premier_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='death_day',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='death_day',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='death_day',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='screenwriter',
            name='death_day',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
