# Generated by Django 4.2.5 on 2023-10-13 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0019_alter_actor_death_day_alter_director_death_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_premier',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
