# Generated by Django 4.2.5 on 2023-10-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0020_alter_movie_world_premier'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='en_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
