# Generated by Django 4.2.5 on 2023-10-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_database', '0021_genre_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
    ]
