services:
  frontend:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    container_name: vue_app_container
    ports:
      - '8080:8080'
    depends_on:
      - backend



  backend:
    build:
      context: .
      dockerfile: ./movies/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=movie_db
      - DB_USER=movie_user
      - DB_PASS=password

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      
    depends_on:
      - database


  database:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=movie_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - movies_data:/var/lib/postgresql/data
    container_name: postgres

volumes:
  movies_data:


