services:
  frontend:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    container_name: ui
    expose:
      - 5137
    depends_on:
      - backend

  backend:
    build:
      context: ./movies
      dockerfile: /Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - /.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database
     # - localstack
    volumes:
      - /home/eugene/Projects/dbmovies/movies/media:/movies/media

  database:
    image: postgres:15.4-alpine
    env_file:
      - ./movies/.env
    ports:
      - "5433:5434"
    volumes:
      - movies_data:/var/lib/postgresql/data
    container_name: postgres

  redis:
    image: redis:7.2-alpine
    hostname: redis

#  localstack:
#    image: localstack/localstack
#    environment:
#      - SERVICES=s3
#      - DEBUG=1
#      - DATA_DIR=/tmp/localstack/data
#    ports:
#      - "4566:4566"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./localstack:/tmp/localstack


volumes:
  movies_data:


