services:
  frontend:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    container_name: vue_app_container
    ports:
      - '8080:8080'
    depends_on:
      - backend



  backend:
    build:
      context: .
      dockerfile: ./movies/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./movies/.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      
    depends_on:
      - database


  database:
    image: postgres:15.4-alpine
    env_file:
      - ./movies/.env
    ports:
      - "5433:5434"
    volumes:
      - movies_data:/var/lib/postgresql/data
    container_name: postgres

  redis:
    image: redis:7.2-alpine
    hostname: redis

volumes:
  movies_data:


