# Generated by Django 4.2.5 on 2023-12-12 19:49

from django.db import migrations, models
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_onlineaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='user'),
        ),
    ]
