# Generated by Django 4.2.5 on 2024-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_critic',
            field=models.BooleanField(default=False),
        ),
    ]
