# Generated by Django 4.2.5 on 2023-12-11 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('GLOBAL', 'Общий чат'), ('DM', 'Личные сообщения'), ('SELF', 'Сохранённое')], default='DM', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
