# Generated by Django 4.2.5 on 2023-12-12 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatting', '0002_alter_chatroom_type_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('GLOBAL', 'Общий чат'), ('DM', 'Личные сообщения'), ('SELF', 'Сохранённое')], default='DM', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('name', 'type')},
        ),
    ]
