name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Create .env file
      run: echo "${{ secrets.DOCKER_ENV_FILE }}" > movies/.env

    - name: Build backend image
      uses: docker/build-push-action@v5
      with:
        context: ./movies
        load: true
        tags: ghcr.io/${{ github.repository_owner }}/dbmovies_backend:latest

    - name: Run unit tests
      run: docker run ghcr.io/${{ github.repository_owner }}/dbmovies_backend python manage.py test movies_database/tests
      env:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: movie_db
        DB_USER: movie_user
        DB_PASSWORD: password

    - name: Push Docker image for backend
      run: docker push ghcr.io/${{ github.repository_owner }}/dbmovies_backend:latest

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./ui
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ github.repository_owner }}/dbmovies_frontend:latest
