name: ci

on:
  pull_request:
    branches: ["master"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Create .env file
      run: echo "${{ secrets.DOCKER_ENV_FILE }}" > movies/.env

    - name: Build docker-compose
      run: docker-compose build

    - name: Run unit tests
      run: docker-compose run backend python manage.py test movies_database/tests

    - name: Tag and push Docker image for backend
      run: |
        docker tag dbmovies_backend ghcr.io/${{ github.repository_owner }}/dbmovies_backend:v.1.0.1
        docker push ghcr.io/${{ github.repository_owner }}/dbmovies_backend:v.1.0.1

    - name: Tag and push Docker image for frontend
      run: |
        docker tag dbmovies_frontend ghcr.io/${{ github.repository_owner }}/dbmovies_frontend:v.1.0.1
        docker push ghcr.io/${{ github.repository_owner }}/dbmovies_frontend:v.1.0.1