name: Build, Test, and Push Docker Image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.0

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Create .env file
      run: echo "${{ secrets.DOCKER_ENV_FILE }}" > movies/.env

    - name: Set up BuildKit
      run: docker buildx create --use

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./movies
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/dbmovies_backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run unit tests
      run: docker run dbmovies_backend python manage.py test movies_database/tests

    - name: Tag and push Docker image for backend to GitHub Container Registry
      run: |
        docker tag dbmovies_backend ghcr.io/${{ github.repository_owner }}/dbmovies_backend:latest
        docker push ghcr.io/${{ github.repository_owner }}/dbmovies_backend:latest

    - name: Tag and push Docker image for frontend to GitHub Container Registry
      run: |
        docker tag dbmovies_frontend ghcr.io/${{ github.repository_owner }}/dbmovies_frontend:latest
        docker push ghcr.io/${{ github.repository_owner }}/dbmovies_frontend:latest