name: Build, Test, and Push Docker Image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # need checkout before using docker-compose-action
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            backend
          test-command: "docker-compose run backend python manage.py test movies_database/tests"